"""align_indexes_and_body_type

Revision ID: 41434641615f
Revises: fe9be9db3276
Create Date: 2026-05-16 00:57:17.595876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41434641615f'
down_revision: Union[str, Sequence[str], None] = 'fe9be9db3276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_article_alive', 'article', ['alive'], unique=False)
    op.create_index('idx_article_author_id', 'article', ['author_id'], unique=False)
    op.create_index('idx_article_create_time', 'article', ['create_time'], unique=False)
    op.create_index('idx_article_updated_time', 'article', ['updated_time'], unique=False)
    op.create_index('idx_article_alive_create_time', 'article', ['alive', 'create_time'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=True)
    op.create_index('idx_user_username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_article_alive_create_time', 'article')
    op.drop_index('idx_article_updated_time', table_name='article')
    op.drop_index('idx_article_create_time', table_name='article')
    op.drop_index('idx_article_author_id', table_name='article')
    op.drop_index('idx_article_alive', table_name='article')
    # ### end Alembic commands ###
