"""increase_body_length

Revision ID: fe9be9db3276
Revises: 
Create Date: 2026-05-15 22:46:11.588037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe9be9db3276'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'body',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=2000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('idx_article_alive'), table_name='article')
    op.create_index(op.f('ix_article_alive'), 'article', ['alive'], unique=False)
    op.create_index(op.f('ix_article_create_time'), 'article', ['create_time'], unique=False)
    op.create_index(op.f('ix_article_updated_time'), 'article', ['updated_time'], unique=False)
    op.alter_column('checkicount', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('checkicount', 'cheki_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkicount', 'cheki_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('checkicount', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_index(op.f('ix_article_updated_time'), table_name='article')
    op.drop_index(op.f('ix_article_create_time'), table_name='article')
    op.drop_index(op.f('ix_article_alive'), table_name='article')
    op.create_index(op.f('idx_article_alive'), 'article', ['alive'], unique=False)
    op.alter_column('article', 'body',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
